"""
AI-Generated Task CRUD API
This is what an AI might produce from the prompt
"""

from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel, Field
from typing import List, Optional
import uvicorn

# Create FastAPI app
app = FastAPI(
    title="Task CRUD API",
    description="Task management API generated by AI",
    version="1.0.0"
)

# Data models
class Task(BaseModel):
    """Task model"""
    id: int
    title: str = Field(..., min_length=1, description="Task title")
    done: bool = Field(default=False, description="Task completion status")

class TaskCreate(BaseModel):
    """Model for creating tasks"""
    title: str = Field(..., min_length=1, max_length=200)

class TaskUpdate(BaseModel):
    """Model for updating tasks"""
    title: Optional[str] = Field(None, min_length=1, max_length=200)
    done: Optional[bool] = None

# Global task storage
TASK_DB: List[Task] = []
TASK_COUNTER = 1

def initialize_tasks():
    """Initialize with sample tasks"""
    global TASK_DB, TASK_COUNTER
    TASK_DB = [
        Task(id=1, title="Learn FastAPI", done=False),
        Task(id=2, title="Build CRUD API", done=False),
        Task(id=3, title="Write documentation", done=True)
    ]
    TASK_COUNTER = 4

# Initialize on startup
initialize_tasks()

@app.get("/", tags=["Info"])
async def root():
    """Get API information"""
    return {
        "name": "Task API", 
        "version": "1.0",
        "endpoints": ["/tasks"]
    }

@app.get("/health", tags=["Health"])
async def health_check():
    """Health check endpoint"""
    return {"status": "ok"}

@app.get("/tasks", response_model=List[Task], tags=["Tasks"])
async def get_tasks(
    done: Optional[bool] = Query(None, description="Filter by completion status"),
    search: Optional[str] = Query(None, description="Search in task titles")
) -> List[Task]:
    """Get all tasks with optional filtering"""
    result = TASK_DB.copy()
    
    if done is not None:
        result = [task for task in result if task.done == done]
    
    if search:
        result = [task for task in result if search.lower() in task.title.lower()]
    
    return result

@app.get("/tasks/{task_id}", response_model=Task, tags=["Tasks"])
async def get_task(task_id: int) -> Task:
    """Get a specific task by ID"""
    task = next((t for t in TASK_DB if t.id == task_id), None)
    if not task:
        raise HTTPException(
            status_code=404, 
            detail=f"Task {task_id} not found"
        )
    return task

@app.post("/tasks", response_model=Task, status_code=201, tags=["Tasks"])
async def create_task(task: TaskCreate) -> Task:
    """Create a new task"""
    global TASK_COUNTER
    
    new_task = Task(
        id=TASK_COUNTER,
        title=task.title,
        done=False
    )
    TASK_DB.append(new_task)
    TASK_COUNTER += 1
    
    return new_task

@app.put("/tasks/{task_id}", response_model=Task, tags=["Tasks"])
async def update_task(task_id: int, updates: TaskUpdate) -> Task:
    """Update an existing task"""
    task = next((t for t in TASK_DB if t.id == task_id), None)
    if not task:
        raise HTTPException(
            status_code=404,
            detail=f"Task {task_id} not found"
        )
    
    if updates.title is not None:
        task.title = updates.title
    if updates.done is not None:
        task.done = updates.done
    
    return task

@app.delete("/tasks/{task_id}", status_code=204, tags=["Tasks"])
async def delete_task(task_id: int):
    """Delete a task"""
    global TASK_DB
    task = next((t for t in TASK_DB if t.id == task_id), None)
    if not task:
        raise HTTPException(
            status_code=404,
            detail=f"Task {task_id} not found"
        )
    
    TASK_DB = [t for t in TASK_DB if t.id != task_id]

@app.get("/stats", tags=["Statistics"])
async def get_statistics():
    """Get task statistics"""
    total_tasks = len(TASK_DB)
    completed_tasks = sum(1 for task in TASK_DB if task.done)
    open_tasks = total_tasks - completed_tasks
    
    return {
        "total": total_tasks,
        "done": completed_tasks,
        "open": open_tasks
    }

@app.post("/reset", tags=["Admin"])
async def reset_database():
    """Reset tasks to initial state"""
    initialize_tasks()
    return {"message": "Database reset successfully", "tasks": TASK_DB}

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)